### ISSUE TITLE
Setup Failing on ubuntu machine

### ISSUE THREAD

**Issue by ramakrishna1592** [rk700/PyMuPDF#90]
First i build mupdf from source provided by ghostscript
Placed the folder within PyFitz folder and than ran the following command

hp@hp-HP-15-Notebook-PC:~/AlgoLeap/poextracter/ToolDev/PyFitz$ sudo python3 setup.py install
running install
running build
running build_py
running build_ext
building 'fitz._fitz' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Wer
ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/mupdf/include/mupdf -I/mupdf/thirdparty/zlib -I/usr/include/
python3.5m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o
fitz/fitz_wrap.c:3033:18: fatal error: fitz.h: No such file or directory
compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Can you let me know if i need to make any changes to the setup file. Unable to understand what i am missing.

**Comment by rk700** [comment]
The header file `fitz.h` cannot be found. Usually it would be in folder `/usr/include` or `/usr/local/include` when `MuPDF` is  installed. So I guess you'll have to figure out where `MuPDF` header files are installed.

**Comment by ramakrishna1592** [comment]
Hi Liu,

![image](https://cloud.githubusercontent.com/assets/13113531/25235482/d9a9cbb8-2602-11e7-845c-c090e85c40de.png)

Folder structure, setup.py file and terminal output.
I have included this path as per your comments above but its still throwing an error

**Comment by rk700** [comment]
Hey @ramakrishna1592,

I guess you could try adding `.../ToolDev/PyFitz/mupdf/include` to `include_dirs` and then build again, since it complains that the file `mupdf/fitz/version.h` is not in header file search path.

**Comment by ramakrishna1592** [comment]
Hi Liu,

added the include folder to the include_dirs. A new error is coming up

ERROR:
![image](https://cloud.githubusercontent.com/assets/13113531/25265471/ef577806-268a-11e7-9059-68b9e429fee7.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265503/13ce41a6-268b-11e7-8788-0625f1ab9c63.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265508/1c0dcb66-268b-11e7-97f9-f6b4fb757d6c.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265521/25c8ab6c-268b-11e7-9d53-1127e18a3012.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265526/3085bcf2-268b-11e7-9d1d-5d7137e52829.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265535/3ade034e-268b-11e7-8ded-da42f988c9a8.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265541/4564dc20-268b-11e7-800f-f6f3b55f8f31.png)
![image](https://cloud.githubusercontent.com/assets/13113531/25265545/4c9374c0-268b-11e7-8c65-16476fc5ab4a.png)

**Comment by rk700** [comment]
Well, it seems that PyMuPDF is not compatible with the MuPDF you use. For example, `fz_convert_pixmap` takes 4 arguments in the MuPDF header file `pixmap.h`, but PyMuPDF is invoking the method with only 3 arguments.

Currently the master branch of PyMuPDF is compatible with MuPDF 1.10a, so you could double check the version of MuPDF.

**Comment by JorjMcKie** [comment]
I saw it coming ...
@ramakrishna1592 - you are using MuPDF v1.11. This is the one on GitHub and also the one you can download from [here](http://mupdf.com/downloads/). Obviously they have stopped providing other / older source versions.

@rk700 is right: PyMuPDF v1.10.0 is incompatible with this MuPDF version, see also this [Wiki](https://github.com/rk700/PyMuPDF/wiki/Change-and-News-Log).

I am going to provide a new PyMuPDF version **1.11.0** during the day in a new branch 1.11.0.
This will be same functionality, but contain the necessary API adjustments.

**Comment by JorjMcKie** [comment]
@ramakrishna1592  - new branch 1.11.0 created. Please download and generate.
It should work with your MuPDF version (no need to re-generate that one).

**Comment by ramakrishna1592** [comment]
@JorjMcKie 

Tried running the install with the new branch. Getting the following Error
![image](https://cloud.githubusercontent.com/assets/13113531/25308120/a509d23e-27cb-11e7-87eb-5fe659ec1e82.png)

Added library_dirs=['./mupdf/build/release'],  getting the following error
![image](https://cloud.githubusercontent.com/assets/13113531/25308122/c2d037fe-27cb-11e7-884a-0d5eb49faee5.png)

using mupdf latest source (1.11) . How do i include these libraries. WHere do i find them in this repository ??

**Comment by rk700** [comment]
@ramakrishna1592 as @JorjMcKie has said, `libmupdf.a` is generated when building MuPDF, and PyMuPDF could not work if MuPDF is build without `-fPIC` option. You could take a look at https://github.com/rk700/PyMuPDF/issues/81 for more information.

**Comment by gileadslostson** [comment]
@ramakrishna1592 if you open the `Makerules` file and amend `CFLAGS` so:
`CFLAGS += -Wall -fPIC` adding the `-fPIC` before compiling it should then work.
Also, make sure your `setup.py` is pointing to the right libraries, etc. That tripped me up something awful.

**Comment by gileadslostson** [comment]
I can confirm that it works on Ubuntu Server 16.10 with `MuPDF 1.11` and `python 3.6.1`

**Comment by JorjMcKie** [comment]
@gileadslostson  - thanks a lot for this confirmation and the help you provided!
Was a little desperate what else we could do ...

**Comment by JorjMcKie** [comment]
In that context, I have to correct myself: older sources (pre - 1.11) of MuPDF **are** still available!
Someone interested may look in the [archive](https://mupdf.com/downloads/archive/) directory. There you can get stuff back to medieval times ...

**Comment by gileadslostson** [comment]
@JorjMcKie to be fair, if you and @rk700  hadn't been such a great help to me last time I would never have been able to do it!
(I also haven't forgotten about the Wiki entry. I am just not sure how to formulate it!)

**Comment by ramakrishna1592** [comment]
@gileadslostson Can you share the process for installation. I have been trying to build mupdf source from ghostscripts repo. It's throwing the following error:
    CC build/release/platform/gl/gl-font.o
In file included from platform/gl/gl-app.h:8:0,
                 from platform/gl/gl-font.c:15:
thirdparty/glfw/include/GLFW/glfw3.h:184:21: fatal error: GL/gl.h: No such file or directory
   #include <GL/gl.h>
                     ^
compilation terminated.
Makefile:116: recipe for target 'build/release/platform/gl/gl-font.o' failed
make: *** [build/release/platform/gl/gl-font.o] Error 1

My current system is Ubuntu 17.04. If you can provide the steps it would be very helpful.

**Comment by gileadslostson** [comment]
@ramakrishna1592 I haven't tried it on 17.04 so I can't be certain. Do you have all the dependencies? Installed?
I took the source directly from MuPDF: https://mupdf.com/downloads/mupdf-1.11-source.tar.gz

Do you need the viewer or just the libraries and tools? If you don't need it, compile using:
`make HAVE_X11=no HAVE_GLFW=no prefix=/usr/local` first then compile again with `make HAVE_X11=no HAVE_GLFW=no prefix=/usr/local install`

**Comment by ramakrishna1592** [comment]
@gileadslostson  I am currently working on building a solution to extract tabular data from pdf's. I have checked out pdfminer and tabula. I am now looking at other libraries to do the same.

**Comment by gileadslostson** [comment]
@ramakrishna1592 I tried them all too but PyMuPDF is, in my opinion, the best tool for it. It is extremely easy to work with (I am working on an online pdf archive. I need to extract data and at times modify the pdf)

- Make sure you have these on your machine: ` freetype2, jbig2dec, libjpeg, openjpeg, and zlib.`
- Download the source directly: `wget https://mupdf.com/downloads/mupdf-1.11-source.tar.gz`
- Edit the `Makefile` to include the `-fPIC` flag. Then run `make HAVE_X11=no HAVE_GLFW=no prefix=/usr/local`

**Comment by JorjMcKie** [comment]
@gileadslostson  - why not call the Wiki something like "Experience from an Ubuntu installation".
And then just make a simple bullet point list would be fine (as you stared one in your above comment). 

Any caveats, (in your opinion) typical problems, and so on, would be helpful. And don't be shy to state the obvious :-). Someone will be grateful!

And btw thanks for your compliments on PyMuPDF's potential - it is really gratifying to read such a reaction.

When I read what you do with PDFs, you might be interested in the coming new features of PyMuDF:

As MuPDF v1.11 supports `EmbeddedFiles` (i.e. attached content like in ZIP archives). SO I decided to give it a try with PyMuPDF. In my private version, I can already deal with such files (actually it is more like general data, not only files). Embedded files of a PDF can be listed, added, extracted and deleted. I am currently writing some scripts for the example directory. Among them: a reporter, a copier between PDFs, exporter and importer. 
Of interest for you?

**Comment by gileadslostson** [comment]
@JorjMcKie I will do the wiki today then (if it is crap please feel free to tell me =D)

And I am definitely interested! I find PyMuPDF really easy to work with and the more I can do with it the better.

**Comment by gileadslostson** [comment]
@JorjMcKie Added the wiki. Hope it is alright!

**Comment by JorjMcKie** [comment]
@gileadslostson - thank you very much, that's fine!
I have included your Wiki in Chapter Installation.

I have also had some trouble to have the `setup.py` code snippet actually show up as code - finally I gave up and changed the editing scheme to restructuredText - sorry about this "intrusion" ...

**Comment by gileadslostson** [comment]
@JorjMcKie no intrusion at all! I just hope it can be of help.

**Comment by ramakrishna1592** [comment]
@gileadslostson @JorjMcKie @rk700 Thanks a lot for helping me out. The same steps as in wiki work for ubuntu 17.04. :)
